apiVersion: apps/v1
kind: Deployment

metadata:
  name: trainee-admin-db-depl
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainee-admin-db
  template:
    metadata:
      labels:
        app: trainee-admin-db
    spec:
      containers:
        - name: trainee-admin-db-container
          image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-admin-db-secret
                  key: password
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: trainee-admin-db-pv
      volumes:
        - name: trainee-admin-db-pv
          persistentVolumeClaim:
            claimName: trainee-admin-db-pvc
              
--- 
#Cluster Ip
apiVersion: v1
kind: Service
metadata:
  name: trainee-admin-db-ip
spec:
  type: ClusterIP
  selector:
    app: trainee-admin-db
  ports:
    - name: trainee-admin-db
      port: 1433
      targetPort: 1433
      protocol: TCP

--- 
#Node Port
apiVersion: v1
kind: Service
metadata:
  name: trainee-admin-db-nodeport
spec:
  type: NodePort
  selector:
    app: trainee-admin-db
  ports:
    - name: trainee-admin-db
      port: 1433
      targetPort: 1433
      nodePort: 32028
      protocol: TCP