// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upgrade.TraineeAdmin.Infrastructure.Contexts;

namespace Upgrade.TraineeAdmin.Infrastructure.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.JobProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("JobProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LevelId = 1,
                            PositionId = 1,
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 2,
                            LevelId = 2,
                            PositionId = 1,
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 3,
                            LevelId = 2,
                            PositionId = 1,
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 4,
                            LevelId = 3,
                            PositionId = 1,
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 5,
                            LevelId = 1,
                            PositionId = 2,
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 6,
                            LevelId = 3,
                            PositionId = 2,
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 7,
                            LevelId = 3,
                            PositionId = 3,
                            TechnologyId = 2
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 952, DateTimeKind.Local).AddTicks(8694),
                            Name = "Basic",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(2444)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3591),
                            Name = "Intermediate",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3601)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3604),
                            Name = "Advanced",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3606)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3608),
                            Name = "Super saiyan ultra hyper god green hair ",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 955, DateTimeKind.Local).AddTicks(3610)
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3818),
                            Name = "Front-end",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3840)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3843),
                            Name = "Back-end",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3845)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3848),
                            Name = "QA Automation",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(3849)
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6228),
                            Name = ".NET",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6241)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6258),
                            Name = "Java",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6260)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6262),
                            Name = "Angular 2",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 956, DateTimeKind.Local).AddTicks(6264)
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentCareerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("OnBoardingDate")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 957, DateTimeKind.Local).AddTicks(5110),
                            CurrentCareerId = 1,
                            OnBoardingDate = new byte[] { 85, 10, 219, 98, 0, 0, 0, 0 },
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 957, DateTimeKind.Local).AddTicks(5114),
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DasId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AddressId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 957, DateTimeKind.Local).AddTicks(242),
                            DasId = "1",
                            Email = "1@gmail.com",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2022, 7, 22, 15, 36, 37, 957, DateTimeKind.Local).AddTicks(257),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.relations.JobProfileTrainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("JobProfileId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobProfileId");

                    b.HasIndex("TraineeId");

                    b.ToTable("JobProfileTrainee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobProfileId = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            JobProfileId = 2,
                            TraineeId = 1
                        });
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.JobProfile", b =>
                {
                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Position");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.Trainee", b =>
                {
                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Upgrade.TraineeAdmin.Domain.Models.relations.JobProfileTrainee", b =>
                {
                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.JobProfile", "JobProfile")
                        .WithMany()
                        .HasForeignKey("JobProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Upgrade.TraineeAdmin.Domain.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobProfile");

                    b.Navigation("Trainee");
                });
#pragma warning restore 612, 618
        }
    }
}
