apiVersion: v1
kind: Service
metadata:
  name: trainee-admin-db-nodeport
spec:
  type: NodePort
  selector:
    app: trainee-admin-db
  ports:
    - name: trainee-admin-db
      port: 1433
      targetPort: 1433
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trainee-admin-srv-extra-nodeport
spec:
  type: LoadBalancer
  selector:
    app: trainee-admin-srv
  ports:
    - name: trainee-admin-srv
      port: 6001
      targetPort: 80